# Generated by Django 4.2 on 2023-04-17 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=270)),
                ('description', models.TextField(blank=True, null=True)),
                ('quarter_pan', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('half_pan', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('full_pan', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('vegan', models.BooleanField(default=False)),
                ('vegetarian', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(blank=True, max_length=64, null=True)),
                ('entree', models.CharField(blank=True, max_length=270, null=True)),
                ('sides', models.CharField(blank=True, max_length=270, null=True)),
                ('beverage', models.CharField(blank=True, max_length=270, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=270)),
                ('description', models.TextField(blank=True)),
                ('size', models.CharField(max_length=270)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
            ],
            options={
                'ordering': ['size', 'price'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=270)),
                ('description', models.TextField(blank=True)),
                ('items', models.ManyToManyField(blank=True, to='catering.item')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=270)),
                ('description', models.TextField(blank=True)),
                ('sections', models.ManyToManyField(blank=True, to='catering.section')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='variations',
            field=models.ManyToManyField(blank=True, to='catering.variation'),
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_size', models.IntegerField(default=4)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('event_time', models.TimeField(blank=True, null=True)),
                ('event_location', models.TextField(blank=True, null=True)),
                ('services_needed', models.TextField(blank=True, null=True)),
                ('equipment_needed', models.TextField(blank=True, null=True)),
                ('special_instructions', models.TextField(blank=True, null=True)),
                ('allergies', models.TextField(blank=True, null=True)),
                ('onsite_cooking', models.BooleanField(default=False)),
                ('menu_items', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer')),
            ],
            options={
                'verbose_name': 'inquiry',
                'verbose_name_plural': 'inquiries',
            },
        ),
    ]
