# Generated by Django 4.2 on 2023-05-04 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0002_menu_available_menu_background_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='type',
            field=models.CharField(blank=True, default='catering', max_length=64, null=True),
        ),
    ]
