# Generated by Django 4.2 on 2023-04-17 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Font',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=80, null=True)),
                ('weight', models.IntegerField(default=400)),
                ('style', models.CharField(default='normal', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('entree', 'Entree'), ('side', 'Side'), ('dessert', 'Dessert'), ('beverage', 'Beverage')], max_length=64)),
                ('title', models.CharField(max_length=270)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('order_options', models.CharField(choices=[('meal', 'meal'), ('individual', 'individual')], default='individual', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('entree', 'Entree'), ('side', 'Side'), ('dessert', 'Dessert'), ('beverage', 'Beverage')], default='entree', max_length=64)),
                ('title', models.CharField(max_length=270)),
                ('description', models.TextField(blank=True)),
                ('items', models.ManyToManyField(blank=True, to='menus.item')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obj_id', models.CharField(blank=True, max_length=64, null=True)),
                ('title', models.CharField(max_length=270)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('available', models.BooleanField(default=True)),
                ('title_color', models.CharField(blank=True, max_length=80, null=True)),
                ('text_color', models.CharField(blank=True, default='white', max_length=80, null=True)),
                ('background_color', models.CharField(blank=True, max_length=80, null=True)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='')),
                ('max_sides', models.IntegerField(default=0)),
                ('sections', models.ManyToManyField(blank=True, to='menus.section')),
                ('title_font', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menus.font')),
            ],
        ),
    ]
