# Generated by Django 4.2 on 2023-04-18 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['price', 'title']},
        ),
        migrations.AddField(
            model_name='menu',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
