# Generated by Django 4.2 on 2023-04-18 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_alter_item_options_menu_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='menu',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
