# Generated by Django 4.2 on 2023-05-04 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0003_alter_menu_options_menu_created_menu_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='type',
            field=models.CharField(blank=True, default='regular', max_length=64, null=True),
        ),
    ]
